# config file for testing

server:
  port: 8080

logging:
  level: info

es:
<<<<<<< HEAD
  host: 10.10.14.6
  port: 9200
  username: elastic
  password: password
=======
  host: 10.10.13.176
  port: 9200
>>>>>>> mongo
