# config file for testing

server:
  port: 8080

logging:
  level: info

es:
  host: log-route-openshift-logging.apps.test2.ocp.c2g.cn
  url: https://log-route-openshift-logging.apps.test2.ocp.c2g.cn
  port: 9200
  token: eyJhbGciOiJSUzI1NiIsImtpZCI6Ii1JTk5sajRqYTJ4VmdUSE1Fb25ySGxtSkFIeURqRVpaUnpOZUlrZ0YwalkifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJvcGVuc2hpZnQtb3BlcmF0b3JzLXJlZGhhdCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VjcmV0Lm5hbWUiOiJlbGFzdGljc2VhcmNoLW9wZXJhdG9yLXRva2VuLXprMm44Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZXJ2aWNlLWFjY291bnQubmFtZSI6ImVsYXN0aWNzZWFyY2gtb3BlcmF0b3IiLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC51aWQiOiIwYzkyZjcwNC00M2RkLTRjNDEtODU0Yy0wZmUxMjExNzdiY2UiLCJzdWIiOiJzeXN0ZW06c2VydmljZWFjY291bnQ6b3BlbnNoaWZ0LW9wZXJhdG9ycy1yZWRoYXQ6ZWxhc3RpY3NlYXJjaC1vcGVyYXRvciJ9.MmFYDWlstcsd5Ao1ED8ezv2l-wVc4xk5Qdi-I6kTNyA_v3pi3l0mQSezYPB4_96ppIwsvj3LDotwLueIoOlAhB3w03RvLl9bgNPAuyIOvPZGmNdRUERnh3HgUn7hnjTuKvspMGSBzggJtdoykMUHe0Ohc0UBSTFg0DKNzaFKlrb2L0hUv1h09AHlGdnLJ8lw4htR8K1nudD_0t5C9tKBrQXG9g2C32PAXlV12_8shWtoqdQ8XpvRAKgz55vMsugn5W8QCaZtsBMGoooiIosAEYwTMiMMlCt9HRx1xkU2oZQmaukmbUhGJux-BAyYsnL6A5r02rQav5jyt5iXgiwEQg