# config file for testing
# filename should be application.yml

app:
  project: examples
  name: gorm-demo
  profiles:
    include:
    - actuator
    - locale
    - logging
    - gorm

logging:
  level: info

