# config file for testing
# filename should be application.yml

app:
  project: hidevopsio
  name: amqp
  profiles:
    include:
    - amqp

amqp:
  host: amqp
  port: 5672
  username: root
  password: 123456

logging:
  level: debug
