# config file for testing

server:
  port: 8080

logging:
  level: debug

#amqp:
#  host: xxxxx
#  port: xxxx
#  username: xxxx
#  password: xxxxxxx

amqp:
  host: 10.10.12.14
  port: 5672
  username: cloudtogo
  password: jYMEBEMCLrybtCr